//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVP_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquilere
    {
        public int AlquilerId { get; set; }
        public int ClienteId { get; set; }
        public int EquipoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal PrecioDiario { get; set; }
        public byte Estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual equipos equipos { get; set; }
    }
}
