//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVP_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquilere
    {
        public int AlquilerId { get; set; }
        public int ClienteId { get; set; }
        public int EquipoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal PrecioDiario { get; set; }
        public byte Estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual equipos equipos { get; set; }
    }
}
