//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVP_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipos()
        {
            this.alquileres = new HashSet<alquilere>();
        }
    
        public int EquipoId { get; set; }
        public string Nombre { get; set; }
        public string Categoria { get; set; }
        public byte Estado { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquilere> alquileres { get; set; }
    }
}
