//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVP_1.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalPrimeDBEntities : DbContext
    {
        public RentalPrimeDBEntities()
            : base("name=RentalPrimeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquilere> alquileres { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
