//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVP_1.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalPrimeDBEntities : DbContext
    {
        public RentalPrimeDBEntities()
            : base("name=RentalPrimeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquilere> alquileres { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
