//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVP_1.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int UsuarioId { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasena { get; set; }
    }
}
